In [1]:
newsum = 1 + 2
newsum

3

In [53]:
import numpy as np
randmatrix = np.matrix(np.random.random((3,5)))
#col1 = randmatrix[:, [1,]]
randmatrix


matrix([[0.89804828, 0.74023144, 0.76084539, 0.64913669, 0.08258748],
        [0.2331672 , 0.58578751, 0.35488615, 0.38412049, 0.83141901],
        [0.08451009, 0.77394472, 0.00574236, 0.26092975, 0.66352385]])

In [59]:
dim = randmatrix.shape
rows = dim[0]
cols = dim[1]

print(dim)
print(rows)
print(cols)
print(randmatrix.shape[0])

(3, 5)
3
5
3


In [60]:
element = randmatrix[1, [0,]]
element

matrix([[0.2331672]])

In [61]:
col1 = randmatrix[:, [0,]]
col1


matrix([[0.89804828],
        [0.2331672 ],
        [0.08451009]])

In [62]:
col2 = randmatrix[:, [1,]]
col2

matrix([[0.74023144],
        [0.58578751],
        [0.77394472]])

In [63]:
#sum(col1[:,[0,]])
newray = []
sumcol = sum(randmatrix[:, [0,]])
sumcol[0,0]
newray.append(sumcol[0,0])#no need to reinitialize
newray
#newray

[1.2157255722093088]

In [64]:
newsum = sum(col1)
save = newsum[0,0]
save

1.2157255722093088

----------------------------------------------------------------------------------------------------------------------

In [65]:
#Creates a random probability matrix (rows sum to one)
import numpy as np
import random
k = 5
m = 3
randmatrix = [[random.uniform(0, 0.1 / k) for i in range(k)] for j in range(m)]
for j, r in enumerate(randmatrix):
    r[j] += 1 - sum(r)
randmatrix = np.array(randmatrix)
randmatrix

array([[0.94947319, 0.01285339, 0.01161693, 0.01723119, 0.0088253 ],
       [0.00711152, 0.9597324 , 0.01990405, 0.00903025, 0.00422178],
       [0.00886053, 0.01450342, 0.9510828 , 0.0094285 , 0.01612475]])

In [66]:
randmatrix[:,1]


array([0.01285339, 0.9597324 , 0.01450342])

In [67]:
#sums all probablilities that read x_i is belongs to species i
#s is an integer value
def numinput0(randmatrix,s):
    col1 = randmatrix[:, [s,]]
    newsum = sum(col1)
    save = newsum[0]
    return save
    
numinput0(randmatrix,1)

0.987089206208129

In [68]:
#l <= column index of species of interest in probability matrix
def deninput0(randmatrix,l):
    #cols = randmatrix[:, [0,l]]
    newarray = []
    j = 0
    while j < l:
        sumcol = sum(randmatrix[:, [j,]])
        newarray.append(sumcol[0])
        j = j + 1
        finalsum = sum(newarray)
    return finalsum
    
deninput0(randmatrix,2)#adjust l based on dimensions
#randmatrix        

1.9525344429972618

In [69]:
pi_num0 = numinput0(randmatrix,0)
pi_den0 = deninput0(randmatrix,2)#adjust l based on dimensions


In [70]:
pi_i = pi_num0 / pi_den0
pi_i

0.4944574679600091

In [72]:
#sums all probablilities that read x_i that belongs to species i where each probability is also multiplied by the estimate
#i = index of species to keep track, usially start at 0th species 
#est is from j-1st iteration
def numiter(randmatrix,i,est):  #in actual code, est = pi_inum
    #cols = randmatrix[:, [0,l]]
    newarray = []
    j = 0 
    bound = (randmatrix.shape[0])
    while j < bound:
        
        element = randmatrix[j, [i,]]*est
        newarray.append(element[0]) 
        j = j + 1
        finalsum = sum(newarray)
    return(finalsum)
    
 

numiter(randmatrix,0,0.2) #for species 0
       

0.19308904735782656

In [73]:
pi_inum = numiter(randmatrix,0,0.2) #adjust pi_inum for jth iteration
pi_inum

0.19308904735782656

In [74]:
def deniter(randmatrix,l,estl):
    sumcols = []
    while l >= 0:
        element = numiter(randmatrix,l,estl) #in actual code, est1 = pi_iden
        sumcols.append(element)
        l -= 1
    #print(sumcols)
    return sum(sumcols)
    
    #c = numiter(randmatrix,l-0,0.2)
    #b = numiter(randmatrix,l-1,0.2)
    #a = numiter(randmatrix,l-2,0.2)
    #return a + b + c
deniter(randmatrix,3,0.2) #for species with index 4

#write an error message for acceptable values for l (must be between [0,number of cols -1])

0.594165633394438

In [75]:
pi_iden = deniter(randmatrix,4,0.2) #adjust pi_iden for jth iteration
pi_iden

0.6000000000000001

In [76]:
pi_ij= pi_inum/pi_iden 
pi_ij

0.3218150789297109

In [85]:
pi_numest4 = numiter(randmatrix,4,pi_numest3)
pi_denest4 = deniter(randmatrix,4,pi_denest3)
estimate4 = pi_numest4/pi_denest4
estimate4

1.0031491471429245e-05

In [84]:
pi_numest3 = numiter(randmatrix,3,pi_numest2)
pi_denest3 = deniter(randmatrix,3,pi_denest2)
estimate3 = pi_numest3/pi_denest3
estimate3

0.001031627816654432

In [83]:
pi_numest2 = numiter(randmatrix,2,pi_numest1)
pi_denest2 = deniter(randmatrix,2,pi_denest1)
estimate2 = pi_numest2/pi_denest2
estimate2

0.08587261599125548

In [80]:
pi_numest1 = numiter(randmatrix,1,pi_numest0)
pi_denest1 = deniter(randmatrix,1,pi_denest0)
estimate1 = pi_numest1/pi_denest1
estimate1

0.256510307488141

In [86]:
pi_numest0 = numiter(randmatrix,0,pi_num0)
pi_denest0 = deniter(randmatrix,0,pi_den0)
estimate0 = pi_numest0/pi_denest0
estimate0

0.49445746796000906

In [87]:
epsilon = 0.07

In [88]:
#pi_numest = pi_num0
#pi_denest = pi_den0
estimatevector= []
estimate = pi_num0/pi_den0
def completealg(randmatrix,epsilon,estimate,pi_num0,pi_den0,probvector):
    estimatevector= []
    for l in  range(randmatrix.shape[1]):
        value = estimate - probvector[l]
        while value < epsilon:
            estimatevector.append(estimate)
            value = epsilon
        pi_numest = numiter(randmatrix,l,pi_num0)
        pi_denest = deniter(randmatrix,l,pi_den0)
        estimate = pi_numest/pi_denest
        pi_num0 = pi_numest
        pi_den0 = pi_denest
            
        l += 1
    return estimatevector
            #pi_num0 = pi_numest
            #pi_den0 = pi_denest
        
    

In [89]:
pi_den0

1.9525344429972618

In [90]:

#estimate = pi_num0/pi_den0
completealg(randmatrix,0.07,0.0596971585842786,0.9740297313839292,1.9492400840211102,[0.02,0.3,0.04,0.24,0.4])

[0.0596971585842786, 0.08456963403456158, 0.0010159744862462713]

In [91]:
def dummy(randmatrix,epsilon,estimate,probvector):    
    estimatevector = []
    for l in range(randmatrix.shape[1]): 
        value = estimate - probvector[l]
        print(value)
        print(value < epsilon)
        while value < epsilon:
            estimatevector.append(estimate)
            value = epsilon #print(estimatevector)
        estimate = estimate - 0.02
        l += 1
    return estimatevector


In [92]:
dummy(randmatrix,0.07,0.0596971585842786,[0.02,0.03,0.04,0.04,0.1])

0.039697158584278594
True
0.009697158584278595
True
-0.020302841415721407
True
-0.04030284141572141
True
-0.12030284141572141
True


[0.0596971585842786,
 0.039697158584278594,
 0.019697158584278594,
 -0.0003028414157214068,
 -0.020302841415721407]

In [93]:
len([1,1,1,1,1])

5

In [94]:
len(range(randmatrix.shape[1]))

5

In [95]:
import numpy as np
import random
k = 2
m = 1000
n = 5
e = 0.1
randomatrix = [[random.randrange(1,n) for i in range(k-1)] for j in range(m)]
randomatrix

[[1],
 [3],
 [2],
 [2],
 [4],
 [2],
 [1],
 [1],
 [4],
 [2],
 [1],
 [3],
 [3],
 [2],
 [4],
 [3],
 [3],
 [3],
 [1],
 [3],
 [3],
 [2],
 [3],
 [4],
 [1],
 [1],
 [3],
 [2],
 [1],
 [2],
 [2],
 [3],
 [4],
 [2],
 [4],
 [4],
 [4],
 [1],
 [2],
 [3],
 [2],
 [2],
 [3],
 [4],
 [2],
 [1],
 [3],
 [4],
 [4],
 [4],
 [4],
 [3],
 [3],
 [4],
 [3],
 [1],
 [4],
 [2],
 [1],
 [4],
 [4],
 [2],
 [4],
 [1],
 [4],
 [3],
 [3],
 [4],
 [2],
 [2],
 [2],
 [3],
 [3],
 [4],
 [3],
 [3],
 [3],
 [2],
 [4],
 [4],
 [2],
 [4],
 [4],
 [4],
 [4],
 [3],
 [3],
 [4],
 [2],
 [3],
 [3],
 [4],
 [2],
 [4],
 [1],
 [1],
 [2],
 [2],
 [2],
 [1],
 [4],
 [2],
 [1],
 [3],
 [4],
 [1],
 [2],
 [4],
 [4],
 [2],
 [4],
 [2],
 [3],
 [4],
 [3],
 [3],
 [4],
 [3],
 [4],
 [3],
 [1],
 [1],
 [3],
 [1],
 [4],
 [1],
 [3],
 [2],
 [1],
 [2],
 [3],
 [4],
 [2],
 [2],
 [3],
 [3],
 [2],
 [4],
 [2],
 [1],
 [1],
 [2],
 [1],
 [1],
 [3],
 [2],
 [3],
 [4],
 [2],
 [4],
 [1],
 [4],
 [4],
 [1],
 [1],
 [4],
 [2],
 [2],
 [3],
 [2],
 [4],
 [1],
 [2],
 [3],
 [4],
 [1],
 [2]

In [96]:
#constructing observation matrix
matrix = []
for j in range(m):
    row = []
    for i in range(k):
        p = random.uniform(0,1)
        #print(p)
        if i == 0 : 
            row.append(random.randrange(0,n))
        elif 0 <= p <= 1- e: #0<= p <= 1-e
            row.append(row[i-1])
        else:
            row.append(random.randrange(1,n)) #want to set frequencies
    matrix.append(row)
matrix

[[3, 3],
 [4, 4],
 [2, 2],
 [0, 0],
 [1, 1],
 [0, 0],
 [1, 1],
 [1, 1],
 [2, 2],
 [3, 3],
 [1, 1],
 [2, 2],
 [0, 0],
 [3, 3],
 [2, 2],
 [1, 1],
 [1, 1],
 [3, 3],
 [0, 0],
 [4, 4],
 [0, 0],
 [4, 4],
 [0, 0],
 [2, 2],
 [3, 3],
 [2, 2],
 [1, 1],
 [0, 0],
 [1, 1],
 [2, 2],
 [1, 1],
 [2, 2],
 [1, 1],
 [2, 2],
 [0, 0],
 [1, 1],
 [2, 2],
 [1, 1],
 [2, 2],
 [1, 1],
 [2, 2],
 [4, 4],
 [1, 1],
 [0, 0],
 [3, 3],
 [0, 4],
 [1, 1],
 [2, 2],
 [2, 2],
 [1, 1],
 [3, 3],
 [0, 0],
 [2, 2],
 [2, 2],
 [1, 1],
 [3, 3],
 [1, 1],
 [1, 1],
 [3, 3],
 [4, 4],
 [3, 3],
 [2, 2],
 [3, 3],
 [1, 1],
 [2, 2],
 [3, 3],
 [1, 1],
 [0, 0],
 [2, 1],
 [2, 2],
 [3, 4],
 [1, 4],
 [4, 4],
 [2, 2],
 [0, 0],
 [4, 4],
 [0, 0],
 [1, 1],
 [4, 4],
 [4, 4],
 [3, 3],
 [0, 0],
 [3, 3],
 [2, 2],
 [3, 3],
 [0, 0],
 [3, 3],
 [0, 0],
 [3, 3],
 [2, 2],
 [3, 3],
 [1, 1],
 [3, 3],
 [3, 3],
 [1, 1],
 [3, 3],
 [0, 0],
 [3, 3],
 [0, 0],
 [2, 4],
 [3, 3],
 [3, 3],
 [1, 1],
 [3, 3],
 [1, 1],
 [0, 0],
 [4, 4],
 [4, 4],
 [2, 2],
 [4, 4],
 [2, 2],
 

In [97]:
datamatrix = [[0 for i in range(n)] for j in range(m)]
for j in range(m):
    for i in range(n):
        if i == matrix[j][1]:
            datamatrix[j][i] = 1-e
        else:
            datamatrix[j][i] = e/(n-1)
#datamatrix
datamatrix = np.array(datamatrix)
datamatrix

array([[0.025, 0.025, 0.025, 0.9  , 0.025],
       [0.025, 0.025, 0.025, 0.025, 0.9  ],
       [0.025, 0.025, 0.9  , 0.025, 0.025],
       ...,
       [0.025, 0.025, 0.025, 0.025, 0.9  ],
       [0.025, 0.025, 0.9  , 0.025, 0.025],
       [0.025, 0.025, 0.025, 0.025, 0.9  ]])

In [98]:
completealg(datamatrix,0.10,0.0596971585842786,0.9740297313839292,1.9492400840211102,[0.02,0.3,0.04,0.24,0.4])

[0.0596971585842786, 0.08996614774405631, 0.024104559299323546]

In [99]:
dummy(datamatrix,0.0,0.0596971585842786,[0.02,0.03,0.04,0.04,0.1])

0.039697158584278594
False
0.009697158584278595
False
-0.020302841415721407
True
-0.04030284141572141
True
-0.12030284141572141
True


[0.019697158584278594, -0.0003028414157214068, -0.020302841415721407]