In [5]:
newsum = 1 + 2
newsum

3

In [6]:
import numpy as np
randmatrix = np.matrix(np.random.random((3,5)))
#col1 = randmatrix[:, [1,]]
randmatrix


matrix([[0.371461  , 0.90723558, 0.88607579, 0.98593723, 0.86521582],
        [0.96111207, 0.7065155 , 0.76992297, 0.35263566, 0.08009033],
        [0.53956396, 0.552414  , 0.12758405, 0.69646087, 0.24588252]])

In [7]:
#matrix = lambda i : randmatrix[i,]/sum(np.array(randmatrix[i,])[0])
randmatrix = matrix(range(randmatrix.shape[0]))
randmatrix 
#probmatrix

#sum(np.array(probmatrix[1,])[0])


#sum(np.array(matrix[0,])[0])
#randmatrix[0,]/sum(np.array(randmatrix[0,])[0])

TypeError: 'list' object is not callable

In [8]:
dim = randmatrix.shape
rows = dim[0]
cols = dim[1]

print(dim)
print(rows)
print(cols)
print(randmatrix.shape[0])

(3, 5)
3
5
3


In [9]:
element = randmatrix[1, [0,]]
element

matrix([[0.96111207]])

In [10]:
col1 = randmatrix[:, [0,]]
col1


matrix([[0.371461  ],
        [0.96111207],
        [0.53956396]])

In [11]:
col2 = randmatrix[:, [1,]]
col2

matrix([[0.90723558],
        [0.7065155 ],
        [0.552414  ]])

In [12]:
#sum(col1[:,[0,]])
newray = []
sumcol = sum(randmatrix[:, [0,]])
sumcol[0,0]
newray.append(sumcol[0,0])#no need to reinitialize
newray
#newray

[1.8721370252152907]

In [13]:
newsum = sum(col1)
save = newsum[0,0]
save

1.8721370252152907

----------------------------------------------------------------------------------------------------------------------

In [64]:
#Creates a random probability matrix (rows sum to one)
import numpy as np
import random
k = 5
m = 3
randmatrix = [[random.uniform(0, 0.1 / k) for i in range(k)] for j in range(m)]
for j, r in enumerate(randmatrix):
    r[j] += 1 - sum(r)
randmatrix = np.array(randmatrix)
randmatrix

array([[0.95733219, 0.00602466, 0.01901064, 0.00874442, 0.00888808],
       [0.01181925, 0.96780526, 0.00242761, 0.01391633, 0.00403154],
       [0.00916359, 0.00441717, 0.97523358, 0.00793296, 0.00325269]])

In [15]:
randmatrix[:,1]


array([0.01755207, 0.96229865, 0.00545091])

In [16]:
#sums all probablilities that read x_i is belongs to species i
#s is an integer value
def numinput0(randmatrix,s):
    col1 = randmatrix[:, [s,]]
    newsum = sum(col1)
    save = newsum[0]
    return save
    
numinput0(randmatrix,1)

0.985301636234249

In [17]:
#l <= column index of species of interest in probability matrix
def deninput0(randmatrix,l):
    #cols = randmatrix[:, [0,l]]
    newarray = []
    j = 0
    while j < l:
        sumcol = sum(randmatrix[:, [j,]])
        newarray.append(sumcol[0])
        j = j + 1
        finalsum = sum(newarray)
    return finalsum
    
deninput0(randmatrix,2)#adjust l based on dimensions
#randmatrix        

1.9836279998259114

In [18]:
pi_num0 = numinput0(randmatrix,0)
pi_den0 = deninput0(randmatrix,2)#adjust l based on dimensions


In [19]:
pi_i = pi_num0 / pi_den0
pi_i

0.503283056943781

In [24]:
#sums all probablilities that read x_i that belongs to species i where each probability is also multiplied by the estimate
#i = index of species to keep track, usially start at 0th species 
#est is from j-1st iteration
def numiter(randmatrix,i,est):  #in actual code, est = pi_inum
    #cols = randmatrix[:, [0,l]]
    newarray = []
    j = 0 
    bound = (randmatrix.shape[0])
    while j < bound:
        
        element = randmatrix[j, [i,]]*est
        newarray.append(element[0]) 
        j = j + 1
        finalsum = sum(newarray)
    return(finalsum)
    
 

numiter(randmatrix,0,0.2) #for species 0
       

0.19966527271833248

In [25]:
pi_inum = numiter(randmatrix,0,0.2) #adjust pi_inum for jth iteration
pi_inum

0.19966527271833248

In [26]:
def deniter(randmatrix,l,estl):
    sumcols = []
    while l >= 0:
        element = numiter(randmatrix,l,estl) #in actual code, est1 = pi_iden
        sumcols.append(element)
        l -= 1
    #print(sumcols)
    return sum(sumcols)
    
    #c = numiter(randmatrix,l-0,0.2)
    #b = numiter(randmatrix,l-1,0.2)
    #a = numiter(randmatrix,l-2,0.2)
    #return a + b + c
deniter(randmatrix,3,0.2) #for species with index 4

#write an error message for acceptable values for l (must be between [0,number of cols -1])

0.595558752452776

In [27]:
pi_iden = deniter(randmatrix,4,0.2) #adjust pi_iden for jth iteration
pi_iden

0.6000000000000001

In [28]:
pi_ij= pi_inum/pi_iden 
pi_ij

0.33277545453055407

In [35]:
pi_numest4 = numiter(randmatrix,4,pi_numest3)
pi_denest4 = deniter(randmatrix,4,pi_denest3)
estimate4 = pi_numest4/pi_denest4
estimate4

3.239937485946833e-06

In [34]:
pi_numest3 = numiter(randmatrix,3,pi_numest2)
pi_denest3 = deniter(randmatrix,3,pi_denest2)
estimate3 = pi_numest3/pi_denest3
estimate3

0.0004377064036394865

In [33]:
pi_numest2 = numiter(randmatrix,2,pi_numest1)
pi_denest2 = deniter(randmatrix,2,pi_denest1)
estimate2 = pi_numest2/pi_denest2
estimate2

0.08257393067355501

In [32]:
pi_numest1 = numiter(randmatrix,1,pi_numest0)
pi_denest1 = deniter(randmatrix,1,pi_denest0)
estimate1 = pi_numest1/pi_denest1
estimate1

0.24998922153710393

In [31]:
pi_numest0 = numiter(randmatrix,0,pi_num0)
pi_denest0 = deniter(randmatrix,0,pi_den0)
estimate0 = pi_numest0/pi_denest0
estimate0

0.503283056943781

In [36]:
epsilon = 0.07

In [37]:
#pi_numest = pi_num0
#pi_denest = pi_den0
estimatevector= []
estimate = pi_num0/pi_den0
def completealg(randmatrix,epsilon,estimate,pi_num0,pi_den0,probvector):
    estimatevector= []
    for l in  range(randmatrix.shape[1]):
        value = estimate - probvector[l]
        while value < epsilon:
            estimatevector.append(estimate)
            value = epsilon
        pi_numest = numiter(randmatrix,l,pi_num0)
        pi_denest = deniter(randmatrix,l,pi_den0)
        estimate = pi_numest/pi_denest
        pi_num0 = pi_numest
        pi_den0 = pi_denest
            
        l += 1
    return estimatevector
            #pi_num0 = pi_numest
            #pi_den0 = pi_denest
        
    

In [38]:
pi_den0

1.9836279998259114

In [39]:

#estimate = pi_num0/pi_den0
completealg(randmatrix,0.07,0.0596971585842786,0.9740297313839292,1.9492400840211102,[0.02,0.3,0.04,0.24,0.4])

[0.0596971585842786, 0.08198559033812218, 0.0004345877397919772]

In [40]:
def dummy(randmatrix,epsilon,estimate,probvector):    
    estimatevector = []
    for l in range(randmatrix.shape[1]): 
        value = estimate - probvector[l]
        print(value)
        print(value < epsilon)
        while value < epsilon:
            estimatevector.append(estimate)
            value = epsilon #print(estimatevector)
        estimate = estimate - 0.02
        l += 1
    return estimatevector


In [41]:
dummy(randmatrix,0.07,0.0596971585842786,[0.02,0.03,0.04,0.04,0.1])

0.039697158584278594
True
0.009697158584278595
True
-0.020302841415721407
True
-0.04030284141572141
True
-0.12030284141572141
True


[0.0596971585842786,
 0.039697158584278594,
 0.019697158584278594,
 -0.0003028414157214068,
 -0.020302841415721407]

In [42]:
len([1,1,1,1,1])

5

In [43]:
len(range(randmatrix.shape[1]))

5

In [90]:
import numpy as np
import random
k = 2
m = 1000
n = 5
e = 0.1
randomatrix = [[random.randrange(1,n) for i in range(k-1)] for j in range(m)]
randomatrix

[[4],
 [2],
 [3],
 [4],
 [2],
 [1],
 [3],
 [3],
 [4],
 [3],
 [4],
 [2],
 [2],
 [3],
 [2],
 [2],
 [1],
 [1],
 [3],
 [1],
 [2],
 [2],
 [4],
 [1],
 [1],
 [1],
 [1],
 [3],
 [3],
 [3],
 [3],
 [1],
 [4],
 [3],
 [1],
 [2],
 [4],
 [4],
 [4],
 [2],
 [2],
 [2],
 [4],
 [2],
 [4],
 [1],
 [4],
 [4],
 [3],
 [3],
 [2],
 [2],
 [3],
 [3],
 [3],
 [3],
 [3],
 [1],
 [2],
 [4],
 [4],
 [3],
 [2],
 [2],
 [2],
 [2],
 [3],
 [2],
 [1],
 [4],
 [2],
 [2],
 [4],
 [4],
 [4],
 [3],
 [1],
 [4],
 [4],
 [2],
 [2],
 [3],
 [2],
 [2],
 [2],
 [1],
 [3],
 [4],
 [3],
 [1],
 [2],
 [2],
 [4],
 [2],
 [2],
 [3],
 [2],
 [3],
 [3],
 [4],
 [2],
 [4],
 [4],
 [4],
 [4],
 [4],
 [1],
 [4],
 [1],
 [4],
 [3],
 [1],
 [4],
 [3],
 [3],
 [3],
 [1],
 [4],
 [1],
 [1],
 [3],
 [3],
 [2],
 [2],
 [3],
 [4],
 [3],
 [4],
 [1],
 [4],
 [4],
 [3],
 [3],
 [4],
 [4],
 [3],
 [2],
 [1],
 [2],
 [1],
 [4],
 [2],
 [1],
 [3],
 [4],
 [3],
 [3],
 [3],
 [2],
 [2],
 [1],
 [3],
 [1],
 [4],
 [2],
 [1],
 [3],
 [4],
 [4],
 [3],
 [3],
 [4],
 [4],
 [4],
 [3],
 [3],
 [1]

In [91]:
#constructing observation matrix
matrix = []
for j in range(m):
    row = []
    for i in range(k):
        p = random.uniform(0,1)
        #print(p)
        if i == 0 : 
            row.append(random.randrange(0,n))
        elif 0 <= p <= 1- e: #0<= p <= 1-e
            row.append(row[i-1])
        else:
            row.append(random.randrange(1,n)) #want to set frequencies
    matrix.append(row)
matrix

[[4, 4],
 [2, 2],
 [0, 0],
 [0, 0],
 [0, 0],
 [1, 1],
 [2, 2],
 [3, 3],
 [2, 2],
 [0, 1],
 [2, 2],
 [2, 2],
 [1, 1],
 [2, 2],
 [0, 0],
 [2, 2],
 [2, 2],
 [2, 2],
 [2, 1],
 [3, 3],
 [2, 2],
 [3, 3],
 [3, 3],
 [0, 0],
 [3, 3],
 [4, 4],
 [2, 2],
 [0, 0],
 [0, 0],
 [3, 3],
 [3, 3],
 [3, 3],
 [0, 0],
 [1, 1],
 [2, 2],
 [0, 0],
 [2, 2],
 [4, 4],
 [2, 2],
 [2, 2],
 [3, 3],
 [0, 0],
 [4, 4],
 [1, 1],
 [0, 0],
 [4, 4],
 [2, 2],
 [2, 2],
 [0, 0],
 [3, 3],
 [1, 1],
 [3, 3],
 [0, 0],
 [2, 3],
 [0, 0],
 [0, 0],
 [2, 2],
 [3, 1],
 [4, 4],
 [2, 2],
 [0, 0],
 [3, 4],
 [4, 4],
 [1, 1],
 [2, 2],
 [2, 2],
 [3, 3],
 [2, 2],
 [4, 4],
 [4, 1],
 [1, 1],
 [0, 0],
 [0, 0],
 [2, 2],
 [4, 4],
 [3, 3],
 [1, 1],
 [0, 0],
 [1, 1],
 [1, 1],
 [2, 2],
 [2, 2],
 [1, 1],
 [4, 4],
 [1, 1],
 [3, 3],
 [1, 1],
 [4, 4],
 [1, 1],
 [2, 2],
 [4, 4],
 [1, 1],
 [2, 2],
 [3, 3],
 [3, 3],
 [0, 0],
 [0, 0],
 [4, 4],
 [3, 3],
 [2, 2],
 [3, 3],
 [4, 4],
 [4, 4],
 [2, 1],
 [1, 1],
 [0, 0],
 [0, 0],
 [1, 1],
 [3, 3],
 [0, 0],
 [2, 2],
 

In [92]:
datamatrix = [[0 for i in range(n)] for j in range(m)]
for j in range(m):
    for i in range(n):
        if i == matrix[j][1]:
            datamatrix[j][i] = 1-e
        else:
            datamatrix[j][i] = e/(n-1)
#datamatrix
datamatrix = np.array(datamatrix)
datamatrix

array([[0.025, 0.025, 0.025, 0.025, 0.9  ],
       [0.025, 0.025, 0.9  , 0.025, 0.025],
       [0.9  , 0.025, 0.025, 0.025, 0.025],
       ...,
       [0.025, 0.9  , 0.025, 0.025, 0.025],
       [0.025, 0.025, 0.9  , 0.025, 0.025],
       [0.9  , 0.025, 0.025, 0.025, 0.025]])

In [95]:
completealg(datamatrix,0.10,0.0596971585842786,0.9740297313839292,1.9492400840211102,[0.02,0.3,0.04,0.24,0.4])

[0.0596971585842786, 0.09339896087375704, 0.022640857151088264]

In [94]:
dummy(datamatrix,0.0,0.0596971585842786,[0.02,0.03,0.04,0.04,0.1])

0.039697158584278594
False
0.009697158584278595
False
-0.020302841415721407
True
-0.04030284141572141
True
-0.12030284141572141
True


[0.019697158584278594, -0.0003028414157214068, -0.020302841415721407]