In [9]:
import numpy as np
randmatrix = np.matrix(np.random.random((3,5)))
#col1 = randmatrix[:, [1,]]
randmatrix


matrix([[0.4034459 , 0.28424562, 0.33478084, 0.55784055, 0.70933031],
        [0.19288153, 0.50583851, 0.65251513, 0.90079335, 0.34502178],
        [0.47772464, 0.83564736, 0.67343308, 0.31499863, 0.99563249]])

In [11]:
col0 = randmatrix[:, [0,]]
col0

matrix([[0.4034459 ],
        [0.19288153],
        [0.47772464]])

In [18]:
row0 = randmatrix[0]
randmatrix[0,1]

0.2842456243547169

In [177]:
d = []
for i in range(randmatrix.shape[1]):
    d.append(randmatrix[0,i])
sum(d)
d = d/sum(d)
d
#sum(d)

array([0.1762047 , 0.12414407, 0.14621528, 0.24363645, 0.30979949])

In [178]:
def stoma(randmatrix):
    final = []
    d = []
    for i in range(randmatrix.shape[1]):
        d.append(randmatrix[0,i])
    sum(d)
    d = d/sum(d)
    d
    return(d)
stoma(randmatrix)

array([0.1762047 , 0.12414407, 0.14621528, 0.24363645, 0.30979949])

In [235]:
import random
k = 5
m = 3
result = [[random.uniform(0, 0.1 / k) for i in range(k)] for j in range(m)]
for j, r in enumerate(result):
    r[j] += 1 - sum(r)
result

[[0.9560138741365427,
  0.009919239975752335,
  0.014701517175389683,
  0.004515101664980619,
  0.014850267047334663],
 [0.019416125236113267,
  0.9577457449952516,
  0.0005844199156102725,
  0.003559079417395432,
  0.01869463043562954],
 [0.0038807079159142257,
  0.007442980603910128,
  0.959627138695936,
  0.009997931489113343,
  0.0190512412951264]]

In [228]:
stomatrix = [ [ 0 for i in range(randmatrix.shape[1]) ] for j in range(randmatrix.shape[0]) ]
stomatrix[:1] = [[3,2,2,2,2]]
stomatrix

[[3, 2, 2, 2, 2], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [221]:
#matrix = lambda i : randmatrix[i,]/sum(np.array(randmatrix[i,])[0])
#randmatrix = matrix(range(randmatrix.shape[0]))
#randmatrix 
#probmatrix

sum(np.array(randmatrix[1,])[0])


#sum(np.array(matrix[0,])[0])
#randmatrix[0,]/sum(np.array(randmatrix[0,])[0])

2.597050301011935